FROM node:14.17-alpine as build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --production

COPY . .

FROM gcr.io/distroless/nodejs:14

WORKDIR /usr/src/app

COPY --from=build /usr/src/app .

EXPOSE 8080

CMD ["app.js"]
